spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sitepulse
    username: sitepulse
    password: sitepulse

sitepulse:
  postgres-dsn: postgresql://sitepulse:sitepulse@localhost:5432/sitepulse
  minio-endpoint: http://localhost:9001
  minio-access-key: admin
  minio-secret-key: password123
  minio-bucket-default: tower-tl
  sync-cron: 0 5/10 * * * *
  detection-sweep-cron: 0 2/10 * * * *
  detection-provider: openai
  dropbox-token: sl.u.AGUxJC04Z717HTwr4-Jt2ayM5qXbQO2eJ42-uqwfR3Gww2lmDw_RADsSSIGt8ckjUStz1rX2zuk-EguRlyesB80eNyD7OIHYig6CEsCP1cUyKx9j1prQ6L4r34TVi4bm6DNfY8hT4crYHiu84Or69kziAdXu6kVjVdeso4d3mUNkCPeNxCwSUFqO83m_5LFABzn7u3A-T44-9tMRVelqVSD-mA8rtcYXFnSUs9cs8yYJ32eDGvK_t3aexRSC4ldSxuYvSmplpeyHzINPvMIUj3lQV3HOhiPwX3aq8pXZsI49RjQ584GjSU4mWTuEDFi5AFrfZyCTxrdNBv_URraGAUYOsflKMVe54SnGrEMTYI6PBCWOIXXrGvVFIWk1N2j7_i4zu6BLg5Iqy_bu8PrMcoGNinwW2DPL2-yMrJarTofqh-4EeL5LpCP-0KQfFvlvGvaXznMO62GfuhoI5DQbUsN0Nbm4k51jYyT_1xxIFR9uvppgSZPHUiBReDmyUc2RFjTZwJ3gD4B_fXFkZIrwXFiZ4el_COFg7wwIwLEYUqZP19oNtsi0Uk3W--HeCbhrTeobmrW-9ZA7_51KfF-xf8Tnu2YHltpi3Oba6588aesK_irY3Puvndyk3wBRbGy513FWj2xJ6ElyZTaP0qK5HJoDKZQRFQHepygv2u48R4zS7akieRPIgJNcRFOMaI8qnCw96oLS-_DK4ByynrpR-qFbuH6yDj7Oe5pXPnUxz6mdHqKfcyRubuhN3pCBLkZYttyH1KeITKsDuJXIuNmcBp1ZwBpCCzSksGdUQX4ndcEcBCqLiiMCDauLjKZLVvuk_12Q4ansRfv3H5Jo6Wji4IvkBKRz_jUWum0rjtYQ0s5cve_uyddQVP8WK5B3MFvMYcFJtYswM1tDELst9PqOoZ7nsHr78lpLeTTnrHKUvhrDAlzeBAJ3XQ6TtNn2UVPnc-KmvtG-NRZLZFwhkXiAPaHQfJiICmbgNHRVxXk6h5or8A58_U3DMEGzu77NtPUzu_xll9OUKNtxbtBFtM0o64xfX0LY_-xGD7Y5SWYdW8OGAPYkYvDbRuk2fo1MkCFfkMEvTS6TrycT5rjj8Pxgi18-FqoBxn189EmU0ubGuQsnVutfsA9OcN5B-3ZiOGdwx1WPrePa4iAjYWXdsP8dRR58lQ3GkCmxDGJDq8B7owbN2UJDYnDXUqfwpfDqW0aukFI9ooiQAOV44LqLExyFMiyCwqMV6tiXtwL1kmq_5J9jn6sBPb_L59QTBERBVVdIjT33k3szWRoI3bpSYbkgiY1Y
  dropbox-app-key: scgiggizvvup4aq
  dropbox-app-secret: 7jgeyny2ff534ep
  dropbox-refresh-token: cM1SFDsV37YAAAAAAAAAAY76lkde5gD5T2YigM9QOjAShzZCehhYNL506oKrfBwA
  openai-model: ${OPENAI_MODEL:gpt-4o}
  python-yolo-base-url: http://localhost:8000
